### ISSUE TITLE
Error while creating a new document

### ISSUE THREAD

**Issue by rajeshtaneja** [jonasfranz/cosmosdb#5]
I am getting following error while creating a new document, can you please help.
```
[+6082 ms] E/flutter (17801): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Exception: Message: {"Errors":["The partition key supplied in x-ms-partitionkey header has fewer components than defined in the the collection."]}
```

Also, can you please update the version in pub.dev to have this feature. Thanks.

**Comment by jonasfranz** [comment]
Have you tried setting the partion key in the CosmosRequestOptions?

**Comment by rajeshtaneja** [comment]
Yeah, after setting Partitionkey, i am getting:
```
{"Errors":["PartitionKey extracted from document doesn't match the one specified in the header. Learn more: https:\/\/aka.ms\/CosmosDB\/sql\/errors\/wrong-pk-value"]}
```

I am passing the correct PartitionKey ... Single string value in list ["uid"]

**Comment by jonasfranz** [comment]
Are you sure that you set the correct partion key? Maybe check on cosmos.azure.com which partion key is used there.

**Comment by rajeshtaneja** [comment]
![image](https://user-images.githubusercontent.com/804487/122201614-ca723800-cece-11eb-89a5-a3f2e97ddad7.png)
Yes It is...

**Comment by jonasfranz** [comment]
Can you check your browser network activity tab for the request the browser is sending to fetch this list?

**Comment by rajeshtaneja** [comment]
Interesting, when I used cosmos web interface to delete the item, I can see it's empty:
![image](https://user-images.githubusercontent.com/804487/122202224-6734d580-cecf-11eb-9d87-4d12f62789a0.png)

**Comment by jonasfranz** [comment]
I've checked my implementation. It seems that you have to set the partion key to the specific value. You have to set it to 123 if the "uid" is "123" for example.

**Comment by rajeshtaneja** [comment]
I agree with you as documentation also say so, but not sure why I have to pass [{}]. 
But that works... I had to modify your package to test this as expected value is String and it won't accept Map.

Any help about why this is happening is appreciated. Also, Thanks for such a quick turn around.

**Comment by rajeshtaneja** [comment]
I got it. Seems like my mistake in creating partion key. 

If the key you set is not in your record, it will set it as {}, so surely an edge case and it would be nice to allow user to set this value as empty map.

**Comment by rajeshtaneja** [comment]
Can you please confirm if https://github.com/jonasfranz/aad_oauth is still working ?
I am unable to compile this. :(

**Comment by rajeshtaneja** [comment]
Can you help me with https://github.com/jonasfranz/aad_oauth
I am unable to get access_code, and I would like to get user profile so I can use it for storing few more related information.

**Comment by jonasfranz** [comment]
@rajeshtaneja I've ended up using another library since the original code quality was not that great.
