### ISSUE TITLE
Publish recent changes

### ISSUE THREAD

**Issue by jgfoster** [jonasfranz/cosmosdb#6]
```
JsonUnsupportedObjectError (Converting object to an encodable object failed: Instance of 'MappedIterable<MapEntry<String, String>, Map<String, String>>')

NoSuchMethodError (NoSuchMethodError: Class 'MappedIterable<MapEntry<String, String>, Map<String, String>>' has no instance method 'toJson'.
Receiver: Instance of 'MappedIterable<MapEntry<String, String>, Map<String, String>>'
Tried calling: toJson())
```

This occurs at `cosmosdb_http_client.dart:60` when trying to do `jsonEncode(body)` where `body` is as shown in the attached screenshot:

![Screen Shot 2021-06-20 at 6 22 39 PM](https://user-images.githubusercontent.com/1577872/122695190-8e9fe100-d1f4-11eb-96e6-28a3771ae59c.png)

I'm trying to follow the code [here:101](https://github.com/jonasfranz/cosmosdb/blob/master/test/api/document_api_test.dart). My code follows:

```
    final results = await _cosmosDB.documents.query(
      Query(
        query:
            'SELECT id FROM $_containerName c WHERE c.id = @id AND c.lockedBy NOT NULL',
        parameters: {
          'id': uuid,
        },
      ),
      database,
      _containerName,
    );
```

I'm on `Dart SDK version: 2.13.1 (stable) (Fri May 21 12:45:36 2021 +0200) on "macos_x64"` and using `json_annotation: 4.0.1` and `cosmosdb: 0.0.3-prerelease`.

**Comment by jgfoster** [comment]
It appears that this is fixed by changes subsequent to 0.0.3-prerelease. Could we get a 0.0.4?

**Comment by jonasfranz** [comment]
Sorry for replying that late. Yes I will release 0.0.4 with your changes soon. Thank you for your contribution :)

**Comment by jonasfranz** [comment]
Released 🎉
